# Generated by Django 3.2.6 on 2021-08-27 12:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0003_alter_organizermodel_user"),
        ("raffles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rafflemodel",
            name="description",
            field=models.TextField(verbose_name="Descripcion"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="end_date",
            field=models.DateTimeField(verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raffles",
                to="organizers.organizermodel",
                verbose_name="Organizador",
            ),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="start_date",
            field=models.DateTimeField(verbose_name="Fecha de inicio"),
        ),
    ]
