# Generated by Django 3.2.6 on 2021-09-08 06:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0004_auto_20210908_0129"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rafflemodel",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="rafflemodel",
            name="max_tickets",
        ),
        migrations.RemoveField(
            model_name="rafflemodel",
            name="min_tickets",
        ),
        migrations.RemoveField(
            model_name="rafflemodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rafflemodel",
            name="ticket_price",
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
