# Generated by Django 3.2.6 on 2021-09-08 06:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0005_auto_20210908_0136"),
    ]

    operations = [
        migrations.AddField(
            model_name="rafflemodel",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rafflemodel",
            name="max_tickets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rafflemodel",
            name="min_tickets",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rafflemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("completed", "Activa"),
                    ("cancelled", "Cancelada"),
                    ("finished", "Terminada"),
                ],
                default="pending",
                max_length=220,
            ),
        ),
        migrations.AddField(
            model_name="rafflemodel",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="name",
            field=models.CharField(max_length=220),
        ),
    ]
