# Generated by Django 3.2.6 on 2021-09-10 07:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0006_auto_20210908_0137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketmodel",
            options={"verbose_name": "Boleto", "verbose_name_plural": "Boletos"},
        ),
        migrations.RemoveField(
            model_name="ticketmodel",
            name="price",
        ),
        migrations.AddField(
            model_name="ticketmodel",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="end_date",
            field=models.DateField(verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="start_date",
            field=models.DateField(verbose_name="Fecha de inicio"),
        ),
    ]
