# Generated by Django 3.2.6 on 2021-09-11 04:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0007_auto_20210910_0214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rafflemodel",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="end_date",
            field=models.DateTimeField(verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="start_date",
            field=models.DateTimeField(verbose_name="Fecha de inicio"),
        ),
    ]
