# Generated by Django 3.2.6 on 2021-09-13 01:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0008_auto_20210910_2317"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketmodel",
            name="identifier",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Identificador"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="end_date",
            field=models.DateField(verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="start_date",
            field=models.DateField(verbose_name="Fecha de inicio"),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="raffle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="raffles.rafflemodel",
            ),
        ),
    ]
