# Generated by Django 3.2.6 on 2021-09-13 06:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0009_auto_20210912_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketmodel",
            name="number",
            field=models.IntegerField(default=1, verbose_name="Número de boleto"),
        ),
        migrations.AlterField(
            model_name="rafflemodel",
            name="ticket_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio de boleto",
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Pagado"),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="Vendidor"),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="is_winner",
            field=models.BooleanField(default=False, verbose_name="Ganador"),
        ),
    ]
