# Generated by Django 3.2.6 on 2021-09-13 07:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0010_auto_20210913_0148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketmodel",
            name="identifier",
        ),
        migrations.AddField(
            model_name="ticketmodel",
            name="code",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Código de boleto"
            ),
        ),
    ]
