# Generated by Django 3.2.6 on 2021-08-27 04:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizermodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="organizers/"),
        ),
    ]
