# Generated by Django 3.2.6 on 2021-08-27 12:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizers", "0002_organizermodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizermodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
